name: Deploy app to S3

on: 
  push:
    branches:
      - main
      - add-cd-pipeline
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: "production"
      with:
        token: ${{ secrets.GITHUB_TOKEN}}
        description: 'Preview my app'
        environment: preview

    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
    
    - name: Get Dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web

    - name: Upload to S3
      uses: shallwefootball/s3-upload-action@master
      id: S3
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: "build/web"
        destination_dir: ''

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_url: https://s3.eu-central-1.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html
        state: 'success'
        deployment_id: ${{ steps.production.outputs.deployment_id }}
